services:
    oro_requirejs.twig.requirejs_extension:
        class: Oro\Bundle\RequireJSBundle\Twig\OroRequireJSExtension
        public: false
        arguments:
            - '@oro_platform.twig.service_locator'
            - '%oro_require_js.web_root%'
            - '%oro_require_js.build_logger%'
        tags:
            - { name: twig.extension }

    oro_requirejs.cache:
        parent: doctrine_cache.abstract.file_system
        public: false
        arguments:
            - '%kernel.cache_dir%/oro_data'
        calls:
            - [ setNamespace, [ 'oro_requirejs' ] ]

    oro_requirejs.config_provider.manager:
        class: Oro\Bundle\RequireJSBundle\Manager\ConfigProviderManager

    oro_requirejs.provider.requirejs_config:
        class: Oro\Bundle\RequireJSBundle\Provider\ConfigProvider
        arguments:
            - '@templating'
            - '@oro_requirejs.cache'
            - '%oro_require_js%'
            - '%kernel.bundles%'
            - '%oro_require_js.web_root%'
        tags:
            - { name: requirejs.config_provider, alias: oro_requirejs_config_provider }
        lazy: true
